2022-04-07 12:04:13,817 - '  ansible.py' - [line: 309] - INFO : {'unreachable': True, 'msg': 'Failed to connect to the host via ssh: wlw@172.16.42.131: Permission denied (publickey,password).', 'changed': False}
2022-04-07 12:04:14,167 - '  ansible.py' - [line: 348] - INFO : {'success': {}, 'failed': {}, 'unreachable': {'172.16.42.131': {'unreachable': True, 'msg': 'Failed to connect to the host via ssh: wlw@172.16.42.131: Permission denied (publickey,password).', 'changed': False}}}
2022-04-07 12:04:14,167 - '  ansible.py' - [line: 375] - INFO : mods/ansible/config/Playbooks/helm.yaml This file  execute failed
2022-04-07 12:04:55,984 - '  ansible.py' - [line: 382] - INFO : This system is not ready
2022-04-07 12:06:29,460 - '  ansible.py' - [line: 348] - INFO : {'success': {'172.16.42.131': {'diff': [], 'dest': './helm', 'src': '/home/wlw/.ansible/tmp/ansible-tmp-1649304386.19359-157346-149806108318086/source', 'md5sum': 'e809f489897f22d78e3b7e16d1c12c7f', 'checksum': '659dc5fabbad2a527c587fe8ab73bdd05d5ab96e', 'changed': True, 'uid': 1000, 'gid': 1000, 'owner': 'wlw', 'group': 'wlw', 'mode': '0664', 'state': 'file', 'size': 45068288, 'invocation': {'module_args': {'src': '/home/wlw/.ansible/tmp/ansible-tmp-1649304386.19359-157346-149806108318086/source', 'dest': 'helm', '_original_basename': 'helm', 'follow': False, 'checksum': '659dc5fabbad2a527c587fe8ab73bdd05d5ab96e', 'backup': False, 'force': True, 'unsafe_writes': False, 'content': None, 'validate': None, 'directory_mode': None, 'remote_src': None, 'local_follow': None, 'mode': None, 'owner': None, 'group': None, 'seuser': None, 'serole': None, 'selevel': None, 'setype': None, 'attributes': None}}, '_ansible_no_log': False}}, 'failed': {'172.16.42.131': {'changed': True, 'stdout': '', 'stderr': "mv: cannot move 'helm' to '/usr/local/bin/helm': Permission denied", 'rc': 1, 'cmd': ['mv', 'helm', '/usr/local/bin/helm'], 'start': '2022-04-07 12:06:27.985585', 'end': '2022-04-07 12:06:27.989052', 'delta': '0:00:00.003467', 'msg': 'non-zero return code', 'invocation': {'module_args': {'creates': '/usr/local/bin/helm', '_raw_params': 'mv helm /usr/local/bin/helm', '_uses_shell': False, 'warn': False, 'stdin_add_newline': True, 'strip_empty_ends': True, 'argv': None, 'chdir': None, 'executable': None, 'removes': None, 'stdin': None}}, 'stdout_lines': [], 'stderr_lines': ["mv: cannot move 'helm' to '/usr/local/bin/helm': Permission denied"], '_ansible_no_log': False}}, 'unreachable': {}}
2022-04-07 12:06:29,461 - '  ansible.py' - [line: 375] - INFO : mods/ansible/config/Playbooks/helm.yaml This file  execute failed
